package com.spok.services.service

import com.spok.model.SpokModel._

/**
 * File contains all the events that are generated by Spok Actor.
 */
object SpokActorEvents {

  case class SpokCreated(spok: Spok, userId: String)

  case class RespokCreated(respok: Respok, spokId: String, userId: String)

  case class UnspokPerformed(unspok: Unspok, spokId: String, userId: String)

  case class CommentAdded(addComment: Comment, spokId: String, userId: String)

  case class CommentUpdated(updateComment: Comment, userId: String)

  case class CommentRemoved(commentId: String, userId: String)

  case class PollAnswerSaved(questionId: String, userId: String, userPollAnswer: UserPollAnswer)

  case class DisabledSpok(spokId: String, userId: String)

  case class RemovedWallSpok(spokId: String, userId: String)

  case class AllPollAnswerSaved(userId: String, allAnswers: AllAnswers)
}
